package service

import (
	"context"
	"encoding/json"
	"fmt"

	appmcp "Supportagent/backend/internal/mcp"
	"Supportagent/backend/internal/policy"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/openai/openai-go/v3"
)

type AIService struct {
	client       openai.Client
	mcpClient    *appmcp.Client
	policyEngine *policy.Engine
}

func NewAIService(
	client openai.Client,
	mcpClient *appmcp.Client,
	policyEngine *policy.Engine,
) *AIService {
	return &AIService{
		client:       client,
		mcpClient:    mcpClient,
		policyEngine: policyEngine,
	}
}

func (s *AIService) GenerateResponse(
	ctx context.Context,
	message string,
) (string, error) {

	// 1. Discover tools from MCP server
	mcpTools, err := s.mcpClient.ListTools(ctx)
	if err != nil {
		return "", fmt.Errorf(
			"failed to list MCP tools: %w",
			err,
		)
	}

	// 2. Convert MCP tool definitions into OpenAI tool definitions
	tools := convertMCPToolsToOpenAITools(mcpTools)

	// 3. Start conversation with the user's message
	messages := []openai.ChatCompletionMessageParamUnion{
		openai.UserMessage(message),
	}

	// 4. Keep running the LLM until it gives a final answer
	for {

		response, err := s.client.Chat.Completions.New(
			ctx,
			openai.ChatCompletionNewParams{
				Model:    openai.ChatModel("openai/gpt-4o-mini"),
				Messages: messages,
				Tools:    tools,
			},
		)

		if err != nil {
			return "", fmt.Errorf(
				"failed to generate response: %w",
				err,
			)
		}

		if len(response.Choices) == 0 {
			return "", fmt.Errorf(
				"LLM returned no choices",
			)
		}

		assistantMessage := response.Choices[0].Message

		// 5. Add the assistant's response to the conversation
		messages = append(
			messages,
			assistantMessage.ToParam(),
		)

		// 6. No tool call means the LLM has produced
		//    the final answer
		if len(assistantMessage.ToolCalls) == 0 {
			return assistantMessage.Content, nil
		}

		// 7. Execute all tools requested by the LLM
		for _, toolCall := range assistantMessage.ToolCalls {

			if toolCall.Type != "function" {
				continue
			}

			// 8. Parse arguments generated by the LLM
			arguments := map[string]any{}

			if err := json.Unmarshal(
				[]byte(toolCall.Function.Arguments),
				&arguments,
			); err != nil {
				return "", fmt.Errorf(
					"failed to parse tool arguments: %w",
					err,
				)
			}

			// 9.1 Check policy before executing a refund.
			if toolCall.Function.Name == "create_refund" {
				orderNumber, ok := arguments["order_number"].(string)
				if !ok || orderNumber == "" {
					return "", fmt.Errorf("create_refund requires order_number")
				}

				// Fetch trusted order data.
				order, err := s.mcpClient.GetOrder(ctx, orderNumber)
				if err != nil {
					return "", fmt.Errorf("failed to fetch order for policy check: %w", err)
				}

				amount, ok := order["total_amount"].(float64)
				if !ok {
					return "", fmt.Errorf("invalid order amount returned by get_order")
				}

				decision := s.policyEngine.Check(
					policy.ActionCreateRefund,
					amount,
				)
				fmt.Printf(
					"POLICY CHECK: action=%s amount=%.2f allowed=%v requiresHuman=%v reason=%s\n",
					policy.ActionCreateRefund,
					amount,
					decision.Allowed,
					decision.RequiresHuman,
					decision.Reason,
				)

				if !decision.Allowed {
					messages = append(
						messages,
						openai.ToolMessage(
							decision.Reason,
							toolCall.ID,
						),
					)
					continue
				}
			}

			//9.2 Call the MCP tool
			result, err := s.mcpClient.CallTool(
				ctx,
				toolCall.Function.Name,
				arguments,
			)
			if err != nil {
				return "", fmt.Errorf("MCP tool call failed: %w", err)
			}

			// 10. MCP can successfully execute the request
			//     but the actual tool can still return an error.
			if result.IsError {

				var errorMessage string

				for _, content := range result.Content {

					if textContent, ok := content.(*mcp.TextContent); ok {
						errorMessage = textContent.Text
						break
					}
				}

				if errorMessage == "" {
					errorMessage = "The tool call failed."
				}

				// Send the actual MCP error back to the LLM.
				messages = append(
					messages,
					openai.ToolMessage(
						errorMessage,
						toolCall.ID,
					),
				)

				continue
			}

			// 11. Successful MCP tool result
			resultJSON, err := json.Marshal(
				result.StructuredContent,
			)

			if err != nil {
				return "", fmt.Errorf(
					"failed to serialize tool result: %w",
					err,
				)
			}

			// 12. Send tool result back to the LLM
			messages = append(
				messages,
				openai.ToolMessage(
					string(resultJSON),
					toolCall.ID,
				),
			)
		}
	}
}

func convertMCPToolsToOpenAITools(
	mcpTools *mcp.ListToolsResult,
) []openai.ChatCompletionToolUnionParam {

	tools := make([]openai.ChatCompletionToolUnionParam, 0)

	for _, tool := range mcpTools.Tools {

		schemaJSON, err := json.Marshal(tool.InputSchema)
		if err != nil {
			continue
		}

		parameters := openai.FunctionParameters{}

		if err := json.Unmarshal(
			schemaJSON,
			&parameters,
		); err != nil {
			continue
		}

		tools = append(
			tools,
			openai.ChatCompletionFunctionTool(
				openai.FunctionDefinitionParam{
					Name:        tool.Name,
					Description: openai.String(tool.Description),
					Parameters:  parameters,
				},
			),
		)
	}

	return tools
}
